import test from 'node:test'
import assert from 'node:assert/strict'
import { validateResearchProposals, evaluateFiniteMilestones } from '../supabase/functions/_shared/research-proposals.js'
const evidence = new Map([['e1',{exactExcerpt:'Replace air filter. 30000 miles or 36 months. 60000 miles or 72 months. Normal. Whichever first. No other notes.'}]])
const ctx = [{evidenceId:'e1',quote:'Replace air filter.'}]
const proposal = () => ({schemaVersion:1,id:'air',name:'Air filter',action:'replace',evidenceIds:['e1'],support:{origin:'provider_claim',row:ctx,actionContext:ctx,headingContext:[{evidenceId:'e1',quote:'30000 miles or 36 months. 60000 miles or 72 months.'}],notesContext:ctx,timingContext:ctx,applicabilityContext:ctx,coverage:'finite_list_only'},schedule:{kind:'milestones',dueSemantics:'whichever_first',milestones:[{miles:30000,months:36,evidenceIds:['e1']},{miles:60000,months:72,evidenceIds:['e1']}],end:{miles:60000,months:72}},blockedReasons:[]})
test('typed claims preserve finite pairs without authenticating source',()=>assert.deepEqual(validateResearchProposals([proposal()],evidence),[proposal()]))
test('reject fabricated source provenance, mismatched spans, endpoint and scope',()=>{for(const mutate of [p=>p.support.origin='server_extracted',p=>p.support.sha256='fake',p=>p.support.row=[{evidenceId:'e1',quote:'invented'}],p=>p.schedule.end.miles=90000,p=>p.schedule.milestones[0].evidenceIds=['foreign'],p=>p.support.notesContext=[]]) {const p=proposal();mutate(p);assert.throws(()=>validateResearchProposals([p],evidence))}})
test('conditional proposals stay blocked',()=>{const p=proposal();p.schedule={kind:'conditional',details:'Oil type and majority use unknown'};assert.throws(()=>validateResearchProposals([p],evidence));p.blockedReasons=['Oil type unknown'];assert.equal(validateResearchProposals([p],evidence)[0].schedule.kind,'conditional')})
test('finite due reports unknown history and anchor; never rebases or extrapolates',()=>{const s=proposal().schedule;assert.equal(evaluateFiniteMilestones(s,{miles:90000}).state,'history_unknown');assert.equal(evaluateFiniteMilestones(s,{historyReviewed:true,miles:100}).state,'in_service_unknown');assert.equal(evaluateFiniteMilestones(s,{historyReviewed:true,miles:30001,ageMonths:1}).state,'due');assert.equal(evaluateFiniteMilestones(s,{historyReviewed:true,miles:1,ageMonths:36}).state,'due');assert.equal(evaluateFiniteMilestones(s,{historyReviewed:true,miles:500,ageMonths:1,completedIndices:[0]}).next.miles,60000);assert.equal(evaluateFiniteMilestones(s,{historyReviewed:true,miles:999999,ageMonths:999,completedIndices:[0,1]}).state,'source_coverage_exhausted')})
