import { ITEM_TYPE_OPTIONS, deriveItemCategory } from './itemModel.js'
const SQL_TYPES=new Set(ITEM_TYPE_OPTIONS.map(option=>option.value))
const TYPE_ALIASES=Object.freeze({vehicle:'car',home:'house',appliance:'electronics',recreation:'other','side by side':'side_by_side','lawn mower':'mower',lawnmower:'mower'})
const FIELD_MAP=Object.freeze({customName:'custom_name',year:'model_year',modelYear:'model_year',manufacturer:'manufacturer',make:'make',model:'model',trim:'trim',modelNumber:'model_number',engine:'engine',engineModel:'engine_model',engineDisplacementLiters:'engine_displacement_liters',engineCylinders:'engine_cylinders',vehicleType:'vehicle_type',bodyStyle:'body_style',plantName:'plant_name',plantCountry:'plant_country',vehicleMarket:'vehicle_market',transmission:'transmission',drivetrain:'drivetrain',fuelType:'fuel_power_type',powerType:'fuel_power_type',serialNumber:'serial_number',engineSerial:'engine_serial',hullNumber:'hull_number',registrationNumber:'registration_number',purchasePrice:'purchase_price',purchaseCurrency:'purchase_currency',purchaseVendor:'purchase_vendor',acquiredOn:'acquired_on',manufacturedOn:'manufactured_on',inServiceOn:'in_service_on',primaryPhotoUrl:'primary_photo_url',usageProfile:'usage_profile',notes:'notes',name:'name',vin:'vin'})
const key=value=>String(value||'').trim().toLowerCase().replace(/[-_]+/g,' ').replace(/\s+/g,' ')
export function toSqlItemType(value){const normalized=key(value);const direct=normalized.replace(/ /g,'_');return SQL_TYPES.has(direct)?direct:TYPE_ALIASES[normalized]||'other'}
export function toSqlUsageDimension(value){const normalized=key(value);if(['miles','mileage'].includes(normalized))return 'mileage';return ['hours','cycles','time'].includes(normalized)?normalized:null}
export function fromSqlUsageDimension(value){const normalized=toSqlUsageDimension(value);return normalized==='mileage'?'miles':normalized}
const compact=value=>typeof value==='string'?(value.trim()||null):value
function identity(values,{patch=false}={}){const result={};for(const [ui,sql] of Object.entries(FIELD_MAP))if(Object.hasOwn(values,ui))result[sql]=compact(values[ui]);for(const field of ['model_year','engine_displacement_liters','engine_cylinders','purchase_price'])if(result[field]!=null)result[field]=Number(result[field]);if(result.purchase_currency)result.purchase_currency=result.purchase_currency.toUpperCase();if(Object.hasOwn(values,'category'))result.category=compact(values.category)||'other';if(Object.hasOwn(values,'itemType'))result.item_type=toSqlItemType(values.itemType);else if(!patch&&Object.hasOwn(values,'category'))result.item_type=toSqlItemType(values.category);if(Object.hasOwn(values,'measurements'))result.usage_dimensions=[...new Set(values.measurements.map(toSqlUsageDimension).filter(Boolean))];if(!patch&&!result.item_type)result.item_type='other';return result}
export function adaptItemDraftToSql(values={}){const result=identity(values);const usage=values.currentUsage||{};for(const [axis,current,origin] of [['miles','current_mileage','origin_mileage'],['mileage','current_mileage','origin_mileage'],['hours','current_hours','origin_hours'],['cycles','current_cycles','origin_cycles']])if(Object.hasOwn(usage,axis)){result[current]=compact(usage[axis]);result[origin]=compact(usage[axis])}return result}
export function adaptItemPatchToSql(values={}){return identity(values,{patch:true})}
export function adaptSqlItem(item={}){const measurements=Array.isArray(item.usage_dimensions)?[...new Set(item.usage_dimensions.map(fromSqlUsageDimension).filter(Boolean))]:[];const selected=new Set(measurements);const currentUsage={};const readings={miles:item.effective_current_mileage??item.current_mileage,hours:item.effective_current_hours??item.current_hours,cycles:item.effective_current_cycles??item.current_cycles};for(const [axis,value] of Object.entries(readings))if(selected.has(axis)&&value!=null)currentUsage[axis]=Number(value);return {...item,category:deriveItemCategory(toSqlItemType(item.item_type||item.category)),itemType:toSqlItemType(item.item_type||item.category),isLocked:Boolean(item.is_locked),measurements,currentUsage}}
