import { useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ITEM_TYPE_OPTIONS, deriveItemCategory, getItemCategoryContract, requiresUsageAndPurchase, selectItemType, supportsVinDecoder, toggleItemMeasurementDraft, validateItemDraft } from '../myStuff/itemModel.js'
import MyStuffVinDecodePanel from '../components/MyStuffVinDecodePanel.jsx'
import { buildCreateMyStuffItemV2WirePayload } from '../myStuff/payloads.js'
import { createMyStuffItemV2 } from '../myStuff/api.js'
import { createMutationAttemptState, mutationIdForPayload, resetMutationAttemptState } from '../myStuff/mutation.js'
import './myStuff.css'
const AXES=[['miles','Miles'],['hours','Hours'],['cycles','Cycles']]
const EMPTY={itemType:'',category:'',measurements:[],currentUsage:{},usageProfile:'normal',purchaseCurrency:'USD'}
export default function MyStuffCreate(){
  const navigate=useNavigate();const [draft,setDraft]=useState(EMPTY);const [errors,setErrors]=useState({});const [backendError,setBackendError]=useState('');const [saving,setSaving]=useState(false);const attempt=useRef(createMutationAttemptState());const inFlight=useRef(false)
  const set=(key,value)=>{setErrors({});setDraft(current=>({...current,[key]:value}))};const setUsage=(axis,value)=>setDraft(current=>({...current,currentUsage:{...current.currentUsage,[axis]:value}}))
  const chooseType=value=>{setErrors({});setDraft(current=>selectItemType(current,value))};const toggle=axis=>setDraft(current=>toggleItemMeasurementDraft(current,axis))
  const applyVinValues=values=>{setErrors({});setDraft(values)}
  async function submit(event){event.preventDefault();if(inFlight.current)return;const payloadDraft={...draft,name:String(draft.name||'').trim(),category:deriveItemCategory(draft.itemType)};const validation=validateItemDraft(payloadDraft,{requireOwnershipFields:true});setErrors(validation.errors);if(!validation.ok)return;const wire=buildCreateMyStuffItemV2WirePayload({...payloadDraft,currentUsage:Object.fromEntries(Object.entries(payloadDraft.currentUsage).filter(([,v])=>String(v).trim()!=='').map(([k,v])=>[k,Number(v)]))});const mutationId=mutationIdForPayload(attempt.current,wire);inFlight.current=true;setSaving(true);setBackendError('');try{const id=await createMyStuffItemV2(wire,mutationId);resetMutationAttemptState(attempt.current);navigate(`/my-stuff/${id}`,{replace:true})}catch(next){setBackendError(next.message||'The item could not be saved. Your retry will safely reuse this attempt.')}finally{inFlight.current=false;setSaving(false)}}
  const allowed=getItemCategoryContract(draft.category)?.measurements||[];const required=requiresUsageAndPurchase(draft.itemType)
  return <main className="mystuff-shell"><header className="mystuff-page-header"><button className="back-btn" type="button" onClick={()=>navigate(-1)} aria-label="Go back">‹</button><h1>Add item</h1></header><form className="mystuff-form" onSubmit={submit} noValidate>
    <fieldset><legend>Identity</legend><Field label="Item name *" name="name" value={draft.name||''} onChange={set} error={errors.name} maxLength="200"/><div className="form-group"><label htmlFor="item-type">Specific item type *</label><select id="item-type" value={draft.itemType} onChange={event=>chooseType(event.target.value)} aria-describedby={errors.itemType?'item-type-error':undefined}><option value="">Choose an item type</option>{ITEM_TYPE_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>{(errors.itemType||errors.category)&&<p id="item-type-error" className="field-error">{errors.itemType||errors.category}</p>}</div>{supportsVinDecoder(draft.itemType)&&<MyStuffVinDecodePanel key={draft.itemType} values={draft} onChange={applyVinValues} disabled={saving} initiallyExpanded preSave/>}<div className="mystuff-columns"><Field label="Model year" name="year" type="number" value={draft.year||''} onChange={set} error={errors.year}/><Field label="Make" name="make" value={draft.make||''} onChange={set}/></div><Field label="Model" name="model" value={draft.model||''} onChange={set}/><Field label="Trim / version" name="trim" value={draft.trim||''} onChange={set}/><div className="mystuff-columns"><Field label="Model number" name="modelNumber" value={draft.modelNumber||''} onChange={set}/><Field label="Serial number" name="serialNumber" value={draft.serialNumber||''} onChange={set}/></div><Field label="Engine / power system" name="engine" value={draft.engine||''} onChange={set}/><div className="mystuff-columns"><Field label="Transmission" name="transmission" value={draft.transmission||''} onChange={set}/><Field label="Drivetrain" name="drivetrain" value={draft.drivetrain||''} onChange={set}/></div><Field label="Fuel / power type" name="fuelType" value={draft.fuelType||''} onChange={set}/></fieldset>
    <fieldset><legend>Ownership & acquisition</legend><Field label="Acquired on" name="acquiredOn" type="date" value={draft.acquiredOn||''} onChange={set} error={errors.acquiredOn}/><Field label={`${required?'Purchase price *':'Purchase price (optional)'}`} name="purchasePrice" type="number" step="0.01" min="0" value={draft.purchasePrice||''} onChange={set} error={errors.purchasePrice}/><div className="mystuff-columns"><Field label="Currency" name="purchaseCurrency" value={draft.purchaseCurrency||''} onChange={set} maxLength="3"/><Field label="Purchased from" name="purchaseVendor" value={draft.purchaseVendor||''} onChange={set}/></div><Field label="Manufactured on" name="manufacturedOn" type="date" value={draft.manufacturedOn||''} onChange={set}/><Field label="In service on" name="inServiceOn" type="date" value={draft.inServiceOn||''} onChange={set}/></fieldset>
    <fieldset><legend>Usage tracking *</legend><p className="mystuff-help">Choose at least one measurement.{required?' Enter a current reading for each selection.':' Readings may be added later.'}</p><div className="mystuff-choices" role="group" aria-describedby={errors.measurements?'measurements-error':undefined}>{AXES.filter(([axis])=>allowed.includes(axis)).map(([axis,label])=><label key={axis}><input type="checkbox" checked={draft.measurements.includes(axis)} onChange={()=>toggle(axis)}/><span>{label}</span></label>)}</div>{errors.measurements&&<p id="measurements-error" className="field-error">{errors.measurements}</p>}{draft.measurements.map(axis=><Field key={axis} label={`Current ${axis}${required?' *':''}`} name={axis} type="number" min="0" step={axis==='cycles'?'1':'any'} value={draft.currentUsage[axis]??''} onChange={(_,value)=>setUsage(axis,value)}/>)}{errors.currentUsage&&<p className="field-error">{errors.currentUsage}</p>}<div className="form-group"><label htmlFor="usage-profile">Usage profile</label><select id="usage-profile" value={draft.usageProfile} onChange={event=>set('usageProfile',event.target.value)}><option value="normal">Normal use</option><option value="severe">Severe use</option></select></div><Field label="Notes (optional)" name="notes" value={draft.notes||''} onChange={set} textarea maxLength="1000"/></fieldset>
    <aside className="mystuff-unavailable">Attachments are not available in My Stuff yet.</aside>{backendError&&<div className="mystuff-error" role="alert">{backendError}</div>}<button className="btn btn-primary" disabled={saving}>{saving?'Saving…':'Add item'}</button>
  </form></main>
}
function Field({label,name,value,onChange,error,textarea=false,...props}){const id=`item-${name}`;const control=textarea?<textarea id={id} value={value} onChange={event=>onChange(name,event.target.value)} aria-describedby={error?`${id}-error`:undefined} {...props}/>:<input id={id} value={value} onChange={event=>onChange(name,event.target.value)} aria-describedby={error?`${id}-error`:undefined} {...props}/>;return <div className="form-group"><label htmlFor={id}>{label}</label>{control}{error&&<p id={`${id}-error`} className="field-error">{error}</p>}</div>}
